### ISSUE TITLE
./metarget gadget install k8s --version=1.16.5 安装时无法运行kubeadm

### ISSUE THREAD

**Issue by jayintro** [Metarget/metarget#115]
docker already installed
uninstalling current kubernetes if applicable
pre-configuring
pre-installing
adding apt repository deb https://mirrors.aliyun.com/kubernetes/apt/ kubernetes-xenial main
installing kubernetes-cni with 0.7.5-00 version
installing kubelet with 1.16.5-00 version
installing kubeadm with 1.16.5-00 version
installing kubectl with 1.16.5-00 version
pulling k8s.gcr.io/pause:3.1
pulling k8s.gcr.io/etcd:3.3.15-0
pulling k8s.gcr.io/coredns:1.6.2
pulling k8s.gcr.io/kube-proxy:v1.16.5
pulling k8s.gcr.io/kube-controller-manager:v1.16.5
pulling k8s.gcr.io/kube-apiserver:v1.16.5
pulling k8s.gcr.io/kube-scheduler:v1.16.5
running kubeadm
error: failed to run kubeadm
error: failed to install k8s

**Comment by brant-ruan** [comment]
如果是在国内，请加上--domestic参数走国内镜像代理。如果还出错，请使用--verbose参数打印一下具体的报错信息。
