### ISSUE TITLE
failed to finish pre-installation

### ISSUE THREAD

**Issue by DavidMitn1ck** [Metarget/metarget#116]
root@ubuntu:/home/k8s-master/Downloads/metarget-0.9.1# ./metarget gadget install k8s --version 1.16.5
docker already installed
uninstalling current kubernetes if applicable
pre-configuring
pre-installing
adding apt repository deb https://mirrors.aliyun.com/kubernetes/apt/ kubernetes-xenial main
error: failed to finish pre-installation
root@ubuntu:/home/k8s-master/Downloads/metarget-0.9.1#

**Comment by brant-ruan** [comment]
Please add `--verbose` option to print error details.

**Comment by Lvzhizheng** [comment]
网络原因，可以多执行几次试试，或者换个docker的源
