### ISSUE TITLE
support removal of kernel

### ISSUE THREAD

**Issue by brant-ruan** [Metarget/metarget#46]
Currently Metarget does not support removal of kernel, which means if we install some vulnerable kernels we must remove them later manually. Metarget should help to delete kernel files which are useless any more.

**Comment by wuheuu** [comment]
请问大概什么时候可以支持这个功能哇，另外请问如果需要删除掉kernel应该怎样操作，可以大致说下思路吗

**Comment by wuheuu** [comment]
@Lvzhizheng 哈咯 请问是已经支持这个功能了吗？请问应当如何操作呢
