### ISSUE TITLE
 recommend that you add a writeup

### ISSUE THREAD

**Issue by RedTeamWing** [Metarget/metarget#59]
可以加一个Writeup的wiki吗，从原理到漏洞复现这样。

**Comment by brant-ruan** [comment]
> 可以加一个Writeup的wiki吗，从原理到漏洞复现这样。

你好，后续会陆续添加，感谢关注！

**Comment by duowen1** [comment]
writeup部分要怎么做贡献呢，刚好做过一些研究和复现，整理过一些资料，但是没有写成英文版。

**Comment by brant-ruan** [comment]
> writeup部分要怎么做贡献呢，刚好做过一些研究和复现，整理过一些资料，但是没有写成英文版。

正在添加`writeups`文件夹和模板，后续更新到master上，打算采用`writeups/cnv_name/README.md`的模式。暂时中文版即可，中文版稳定、成规模后视需求启动英文的翻译。

**Comment by brant-ruan** [comment]
@duowen1 可参照[writeups_cnv/](https://github.com/brant-ruan/metarget/tree/master/writeups_cnv)的说明和[示例](https://github.com/brant-ruan/metarget/tree/master/writeups_cnv/mount-host-procfs)的内容结构来添加writeup
